### PR TITLE
Export platform-specific symbol sets

### LINKED ISSUE #30: Please consider exporting `main` & `windows`
I am trying to test the CLI of a cross-platform app that uses inquirer, which depends upon `figures`.

The issue is that tests fail with 
```
  -       >( ) Pepperoni␊
  -        ( ) Ham␊
  -        ( ) Ground Meat␊
  -        ( ) Bacon␊
  +       ❯◯ Pepperoni␊
  +        ◯ Ham␊
  +        ◯ Ground Meat␊
  +        ◯ Bacon␊
            = The Cheeses = ␊
  -        (*) Mozzarella␊
  +        ◉ Mozzarella␊
```

The test can easily replace the output to have a normalized form of figures when CLI is being tested so this does not occur. However, currently, there is no programatic way to getting to the `figures.windows` symbols on my `macos` (or vice versa). 

I can create a manual copy, but that seems brittle.

### PR DESCRIPTION
**Pull request by Richienb**
Signed-off-by: Richie Bendall <richiebendall@gmail.com>

Closes #30 

cc @sindresorhus

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -1,3 +1,7 @@
+declare interface FigureSet {
```
Comment (sindresorhus) [inline index.d.ts]: Needs a doc comment on what it is and how it's useful. Preferably with an example.

This needs to be documented in the readme too.

**Comment by Richienb** [comment]
@sindresorhus Ready for re-review!
